x-base_service: &base_service
    init: true
    ports:
      - "8188:8188"
    stop_signal: SIGKILL
    tty: true
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu, compute, utility]

services:
  comfy:
    <<: *base_service
    volumes:
      - "./comfy/storage:/root"
    profiles: ["comfy"]
    build: ./comfy/
    image: "comfy:comfy"
    environment:
      - CLI_ARGS=

  comfy3d:
    <<: *base_service
    volumes:
      - "./comfy_3d_pack/storage:/root"
    profiles: ["comfy_3d_pack"]
    build: ./comfy_3d_pack/
    image: "comfy_3d_pack:comfy_3d_pack"
    environment:
      - CLI_ARGS=
